---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "name" . }}
  labels:
{{ include "labels" . | indent 4 }}
rules:
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - networks
  - networks/status
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - list 
  - watch 
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - networking-calico-leader-election
  - gardener-extension-heartbeat 
  verbs:
  - get
  - update
- apiGroups:
  - resources.gardener.cloud
  resources:
  - managedresources
  verbs:
  - get
  - list
  - create
  - delete
  - watch
  - patch
  - update
- apiGroups:
  - ""
  - apps
  - batch
  - rbac.authorization.k8s.io
  - admissionregistration.k8s.io
  - apiextensions.k8s.io
  - monitoring.coreos.com
  resources:
  - namespaces
  - events
  - secrets
  - configmaps
  - endpoints
  - deployments
  - deployments/scale
  - services
  - serviceaccounts
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  - jobs
  - pods
  - pods/log
  - mutatingwebhookconfigurations
  - customresourcedefinitions
  - scrapeconfigs
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "name" . }}
  labels:
{{ include "labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
